### ISSUE TITLE
Cheating the browsers cache when a JS file is updated

### ISSUE THREAD

**Issue by remiolsen** [SciLifeLab/genomics-status#112]
Some of the JS code we've moved out from the template and to separate files, it would be nice if they didn't get cached by the browsers when we add/change some code.

Maybe it would be possible to add the commit id's of the current files in the templates, thusly
```
<script type="text/javascript" src="somescript.js?{latest git commit id}"></script>
```

As suggested by @ewels in the the discussion here: https://github.com/SciLifeLab/status/pull/100

**Comment by ewels** [comment]
Fixed in #188
