### ISSUE TITLE
Shore up HTML safety in running notes

### ISSUE THREAD

**Issue by ewels** [SciLifeLab/genomics-status#159]
Joel discovered that any HTML you write in running notes is dumped straight out in the browser. Whilst quite handy for people wanting to write links and stuff, we should probably limit which HTML tags we allow (and maybe strip attributes).

Can probably strip everything simply with `$("<p>").html(running_note).text();` - though we may want to make it slightly more complex so that we can keep links etc. _May_ be easier to do this server side.

**Comment by Galithil** [comment]
Went for markdown in the end.
