### ISSUE TITLE
Clean up suggestion_box database

### ISSUE THREAD

**Issue by guillermo-carrasco** [SciLifeLab/genomics-status#172]
When issue #171 is fixed, clean up repeated suggestions in the database

**Comment by ewels** [comment]
Whut? I guess this is probably done?? 😅

**Comment by guillermo-carrasco** [comment]
![hi](https://user-images.githubusercontent.com/1574147/44669630-ac3aa500-aa20-11e8-82de-1adecd5bbfb8.gif)
